appointments/urls.py

from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/appointments/', views.list_appointments, name='admin_list_appointments'),
    path('admin/appointments/cancel/<int:appointment_id>/', views.cancel_appointment, name='admin_cancel_appointment'),
    path('admin/appointments/add/', views.AppointmentCreateView.as_view(), name='add_appointment'),
    path('admin/appointments/edit/<int:pk>/',views.AppointmentUpdateView.as_view(), name='edit_appointment'),
    path('book/',views.book_appointment ,name='book_appointment'),
    path('success/<int:appointment_id>/', views.success, name='success'),

]

dentalhealthyclinic/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from django.conf.urls import handler404
from .error_handlers import Error404View,ForbiddenView

handler403 = ForbiddenView.as_view()
handler404 = Error404View.as_view()
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('appointments/', include('appointments.urls')),
    path('contact/', include('contact.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('dservices/', include('dservices.urls')),
    path('pay/', include('pay.urls')),
    path('profiles/', include('profiles.urls')),
    path('fee/', include('fee.urls')),
    path('reviews/', include('reviews.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fee/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.fees_list, name='fees'),
]

appointments/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from fee.models import Fee




class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    base_price = models.DecimalField(max_digits=10, decimal_places=2)
    def __str__(self):
        return f'{self.name}'



class Dentist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='dentist')
    services = models.ManyToManyField(Fee, related_name='dentists', blank=True) 

    def __str__(self):
        return self.user.get_full_name()





class Appointment(models.Model):
    full_name = models.CharField(max_length=100,null=True)
    email = models.EmailField(null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    phone_number = models.CharField(max_length=20,null=True) 
    dentist = models.ForeignKey(Dentist, on_delete=models.CASCADE, blank=True, null=True, related_name='appointments')
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    
    service = models.ForeignKey(Fee, on_delete=models.CASCADE, null=True)
    STATUS_CHOICES = (
        ('Scheduled', 'Scheduled'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Scheduled')
    notes = models.TextField(blank=True)
    reference_number = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return f"Appointment - {self.reference_number}"

appointments/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Service,Appointment,Dentist
from .utils import generate_appointment_qr_code
from .forms import AppointmentForm
from fee.models import Fee  
import random
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic import  CreateView, UpdateView
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from django.contrib import messages 
from django.db import transaction  
from django.core.exceptions import PermissionDenied

from django.contrib.auth.decorators import login_required,user_passes_test

#check for as admin -------------
# Check if the user is an admin
def is_admin(user):
    if not user.is_authenticated or not user.is_superuser:
        raise PermissionDenied("You do not have permission to perform this action.")
    else:
        return True

class AdminRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_superuser

    def handle_no_permission(self):
        raise PermissionDenied("You do not have permission to perform this action.")

@login_required(login_url='/accounts/login/')
@user_passes_test(is_admin)
def list_appointments(request):
    appointments = Appointment.objects.all().order_by('date', 'time')
    return render(request, 'appointments/admin_list.html', {'appointments': appointments})

login_required(login_url='/accounts/login/')
@user_passes_test(is_admin)
def cancel_appointment(request, appointment_id):
   
    appointment = get_object_or_404(Appointment, id=appointment_id)
    appointment.status = 'Cancelled'
    appointment.save()
    try:
        customer_email = appointment.email
        subject = render_to_string(
            'appointments/confirmation_emails/confirmation_email_cancellation_subject.txt',
            {'appointment': appointment}
        )
        body = render_to_string(
            'appointments/confirmation_emails/confirmation_email_cancellation_body.txt',
            {'appointment': appointment, 'contact_email': settings.DEFAULT_FROM_EMAIL}
        )

        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [customer_email])
        messages.success(request, f'Appointment has been cancelled and a cancellation email has been sent to {appointment.email}.')
    except Exception as e:
        messages.error(request, f'There was an error sending the cancellation email: {e}')

    return redirect('admin_list_appointments')



# Create Appointment
class AppointmentCreateView(LoginRequiredMixin, AdminRequiredMixin, CreateView):
    model = Appointment
    form_class = AppointmentForm
    template_name = 'appointments/appointment_form.html'
    success_url = reverse_lazy('admin_list_appointments')
    def form_valid(self, form):
        response = super().form_valid(form)  # Save the appointment
        messages.success(self.request, 'Appointment created successfully!')

        # Send notification email to the user (if email exists)
        if self.object.email:  # self.object is the saved Appointment instance
            try:
                customer_email = self.object.email
                subject = render_to_string(
                    'appointments/confirmation_emails/admin_create_appointment_subject.txt', 
                    {'appointment': self.object}
                )
                body = render_to_string(
                    'appointments/confirmation_emails/admin_create_appointment_body.txt',
                    {'appointment': self.object, 'contact_email': settings.DEFAULT_FROM_EMAIL}
                )
                send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [customer_email])
            except Exception as e:
                # Handle email sending errors (e.g., log them)
                pass 
        
        return response

# Update Appointment
class AppointmentUpdateView(LoginRequiredMixin, AdminRequiredMixin, UpdateView):
    model = Appointment
    form_class = AppointmentForm
    template_name = 'appointments/appointment_form.html'
    success_url = reverse_lazy('admin_list_appointments')

    def form_valid(self, form):
        response = super().form_valid(form)  # Save the appointment
        messages.success(self.request, 'Appointment updated successfully!')

        # Send notification email 
        if self.object.email:  # self.object is the saved Appointment instance
            try:
                customer_email = self.object.email
                subject = render_to_string(
                    'appointments/confirmation_emails/admin_update_appointment_subject.txt', 
                    {'appointment': self.object}
                )
                body = render_to_string(
                    'appointments/confirmation_emails/admin_update_appointment_body.txt',
                    {'appointment': self.object, 'contact_email': settings.DEFAULT_FROM_EMAIL}
                )
                send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [customer_email])
            except Exception as e:
                # Handle errors 
                pass 
        
        return response




#=====================================

@login_required(login_url='/accounts/login/')
def success(request, appointment_id):
    """
    Handle successful appointments
    """
    appointment = Appointment.objects.get(id=appointment_id)
    qr_code_data = generate_appointment_qr_code(appointment)
    # Send Confirmation Email
    try:
        customer_email = appointment.email
        subject = render_to_string(
            'appointments/confirmation_emails/confirmation_email_subject.txt',  # Adjust template path
            {'appointment': appointment}
        )
        body = render_to_string(
            'appointments/confirmation_emails/confirmation_email_body.txt',  # Adjust template path
            {'appointment': appointment, 'contact_email': settings.DEFAULT_FROM_EMAIL}
        )

        send_mail(subject, body, settings.DEFAULT_FROM_EMAIL, [customer_email])
        messages.success(request, f'Appointment confirmed! A confirmation email has been sent to {appointment.email}.',extra_tags='bag_related=False')

    except Exception as e:  
        messages.error(request, f'There was an error sending the confirmation email: {e}')



    return render(request, 'appointments/success.html', {'appointment': appointment,'qr_code_data': qr_code_data})



@login_required(login_url='/accounts/login/') 
def book_appointment(request):
    """
    Handles the booking of a new dental appointment.

    This view function:
    1. Renders the appointment booking form with available fees.
    2. Processes the form submission, validating the data.
    3. Assigns a random dentist who offers the selected service (if available).
    4. Checks for conflicting appointments with the chosen dentist and time.
    5. Saves the appointment if no conflicts are found.
    6. Redirects to a success page or re-renders the form with errors.

    If the user is authenticated, it also attempts to prefill the 'full_name' field from their last appointment.

    Args:
        request: The HttpRequest object representing the current request.

    Returns:
        HttpResponse: An HTTP response containing either:
            - The rendered appointment booking form (on GET request or invalid POST data).
            - A redirect to a success page (on successful appointment booking).
    """
    fees = Fee.objects.all()
    if request.method == 'POST':
        form = AppointmentForm(request.POST) 
        if form.is_valid():
            
            appointment = form.save(commit=False)
            appointment.user = request.user

                # Get selected service
            selected_fee = form.cleaned_data['service']

                # Get all dentists who offer the selected service
                #available_dentists = Dentist.objects.filter(services__service=selected_fee.service)
            available_dentists = Dentist.objects.filter(services=selected_fee)


            # If there are available dentists, randomly choose one
            if available_dentists.exists():
                appointment.dentist = random.choice(available_dentists)
            else:
                messages.error(request, "No dentists are available for this service at the moment.")
                return render(request, 'appointments/book_appointment.html', {'form': form, 'fees': fees})

            # Check for existing appointment at the same time and dentist
            try:
                existing_appointment = Appointment.objects.get(
                    dentist=appointment.dentist,
                    date=form.cleaned_data['date'],
                    time=form.cleaned_data['time']
                )
                messages.error(request, "This time slot is already booked. Please choose another time.")
                return render(request, 'appointments/book_appointment.html', {'form': form, 'fees': fees})
            except Appointment.DoesNotExist:
                pass  # No conflict, proceed with booking

            appointment.save()  
            return redirect('success', appointment_id=appointment.id)
    else:
        
        initial_data = {}
        if request.user.is_authenticated:
            

            initial_data['email'] = request.user.email
            try:
                # Get the latest appointment for the user
                #previous_appointment = Appointment.objects.filter(email=request.user.email).order_by('-date', '-time').first()

appointments/templates/appointments/admin_list.html
{% extends "base.html" %}
{% block cortitle  %}admin lists{% endblock %}
{% block page%}admin_list{% endblock %}
{% block content %}

<h1>All Appointments</h1>
<a href="{% url 'add_appointment' %}" class="btn btn-success my-3 rounded-pill">Add Appointment</a>
<div class="table-responsive p-1 ">
<table class="table table-striped fs-6">
    <thead>
        <tr>
            <th class="d-none d-md-table-cell">Reference</th>
            <th>Full Name</th>
            <th class="d-none d-md-table-cell">Email</th>
            <th>Date</th>
            <th>Time</th>
            <th>Service</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in appointments %}
        <tr class="border border-info-subtle">
            <td class="d-none d-md-table-cell mt-auto">{{ appointment.reference_number }}</td>
            <td>{{ appointment.full_name }}</td>
            <td class="d-none d-md-table-cell">{{ appointment.email }}</td>
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.time|date:"H:i" }}</td>
            <td>{{ appointment.service }}</td>
            <td >{{ appointment.status }}</td>
            <td >
                {% if appointment.status != 'Cancelled' %}
                <a href="{% url 'edit_appointment' appointment.id %}" class="btn btn-primary btn-sm nav-justified w-100 my-1">Edit</a>
                <a href="{% url 'admin_cancel_appointment' appointment.id %}" class="btn btn-danger w-100">Cancel</a>
                {% else %}
                <a href="{% url 'edit_appointment' appointment.id %}" class="btn btn-outline-primary btn-sm disabled  w-100 my-1 " >Edit</a>
                <a href="{% url 'admin_cancel_appointment' appointment.id %}" class="btn btn-outline-danger disabled  w-100" >Cancel</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

appointments/templates/appointments/appointment_form.html
{% extends "base.html" %}
{% block cortitle  %}admin booking{% endblock %}
{% block page%}admin_booking{% endblock %}
{% block content %}
<div class="container mt-5 mb-3">
    <h3><u>Admin {% if form.instance.pk %}Edit{% else %}Add{% endif %} Appointment </u></h3>
    
    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}  
        <button type="submit" class="btn btn-primary">
            {% if form.instance.pk %}Update{% else %}Add{% endif %} Appointment
        </button>
        <a href="{% url 'admin_list_appointments' %}" class="btn btn-secondary rounded-pill my-2">Cancel</a>
    </form>
</div>
{% endblock %}

appointments/templates/appointments/book_appointment.html
{% extends 'base.html' %}
{% block cortitle  %}Book appointment{% endblock %}
{% block page%}book_appointment{% endblock %}
{% block content %}

<div class="container align-items-center  p-2  bg-light rounded-4 mt-4 ">

    <hr>
    <p class="h2 logo-font mb-4 text-center">Book an Appointment</p>
    <hr>


    {{ form.media }}
    <form method="POST" class="flex-column">
        {% csrf_token %}
        
        {{ form|crispy}}
        

        {% if not user.is_authenticated %}
            {{ form.email }} 
        {% else %}
{% comment %}             <input type="email" name="email" id="id_email" value="{{ user.email }}" hidden> {% endcomment %} 
    <input type="hidden" name="email" value="{{ user.email }}">

        {% endif %}
        
        <button type="submit" class="btn btn-primary">Book Appointment</button>
    </form>
</div> 


{% endblock %}

{% comment %} <div class="container align-items-center  p-2  bg-light rounded-4">

    <hr>
    <p class="h2 logo-font mb-4">Book an Appointment</p>
    <hr>


    {{ form.media }}
    <form method="POST" class="flex-column">
        {% csrf_token %}

        {% if form.full_name.value %}  
            <div class="form-group">
                <label for="id_full_name">Full Name:</label>
                <input type="text" name="full_name" id="id_full_name" class="form-control" value="{{ form.full_name.value }}" required>
            </div>
        {% else %}
            {{ form.full_name|as_crispy_field }} 
        {% endif %}
        

        {{ form.phone_number|as_crispy_field }}

        {% if not user.is_authenticated %}
            {{ form.email|as_crispy_field }} 
        {% else %}
            <input type="email" name="email" id="id_email" value="{{ user.email }}" hidden>
        {% endif %}
        
        {{ form.date|as_crispy_field }}
        {{ form.time|as_crispy_field }}
        {{ form.service|as_crispy_field }}
        {{ form.notes|as_crispy_field }}

        <button type="submit" class="btn btn-primary">Book Appointment</button>
    </form>
</div> {% endcomment %}


appointments/templates/appointments/success.html

{% extends "base.html" %}
{% block cortitle  %}booked{% endblock %}
{% block page%}booked_app{% endblock %}
{% block content %}


<div class="container mt-5 booked_app_card w-100" > 
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-success text-white">
                    <h2 class="card-title">Appointment Booked Successfully!</h2>
                </div>
                <div class="card-body">
                    <img src="data:image/png;base64,{{ qr_code_data|safe }}" alt="Appointment QR Code" class="w-50" >
                    <h5 class="card-subtitle mb-3 text-muted">
                        <strong>Booking Reference Number:</strong> {{ appointment.reference_number|stringformat:"s"|slice:":6" }}
                    </h5>
                    
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">Full Name:</th>
                                <td>{{ appointment.full_name }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Phone Number:</th>
                                <td>{{ appointment.phone_number }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Email:</th>
                                <td>{{ appointment.email }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Dentist:</th>
                                <td>{{ appointment.dentist }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Date:</th>
                                <td>{{ appointment.date }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Time:</th>
                                <td>{{ appointment.time }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Service:</th>
                                <td>{{ appointment.service }}</td>
                            </tr>
                            {% if appointment.notes %}
                            <tr>
                                <th scope="row">Notes:</th>
                                <td>{{ appointment.notes }}</td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                    
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary mt-3" onclick="window.print()">Print Appointment Details</a>
                   

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}